server:
  port: 8081
spring:
  application:
    name: admin-client
  boot:
    admin:
      client:
        url: http://localhost:8080
management:
  endpoints:
    web:
      exposure:
        include: '*'
    health:
      show-details: always

